### PR TITLE
update service name

### PR DESCRIPTION
**Pull request by nubz**
https://jira.tools.tax.service.gov.uk/browse/HEC-1176 <-- ticket to do this

### CODE REVIEW

**Comment by priyankadhiman3006** [comment]
i think build failed

**Comment by priyankadhiman3006** [comment]
some test cases have failed

**Comment by meghana-viswanath** [comment]
> some test cases have failed

looks like the injected `TimeProvider` isn't being used on the `taxSituationSubmit` api and we just went over a threshold, I'll take a look at this 👍

**Review by AndyHWChung — APPROVED** [review]

**Comment by meghana-viswanath** [comment]
@nubz if you rebase over latest master, the build should be fixed

**Pull request merged**
